### PR TITLE
tally, squad, hut: reskin

### PR DESCRIPTION
**Pull request by matildepark**
- Reskinned both Squad and Hut to match Foundation design
- Migrate Hut to Vite build system so you can proxy on top of a running ship instead of constantly globbing to see changes
- Import foundation-design-system and use its Tailwind config
- Downgrade React to React 17 to prevent npm complaining about peer dependency mismatch (Even though we don't use any React-specific stuff in FDS here, we don't want to tell users to `—-force` it)
- Because we use foundation-design-system we also get the automatic dark mode we see on urbit.org. Neat.
- Fixes an issue where we would subscribe twice on mount causing all chat messages to come in twice. This is apparently because of the `<React.StrictMode>` wrapper; normally you'd call the API differently I think so we don't usually see this bug.

Squad:

Screen Shot 2022-08-24 at 12 22 40 PM

Hut:

Screen Shot 2022-08-24 at 12 19 13 PM
Screen Shot 2022-08-24 at 12 19 33 PM

### CODE REVIEW

**Comment by matildepark** [comment]
Screen Shot 2022-09-06 at 6 33 51 PM
Screen Shot 2022-09-06 at 6 34 04 PM

**Comment by gordoncc** [comment]
Vast improvement already.  My feedback below:

Squad 
- Let's be consistent with capitalization and capitalize Join, Create, and Squads 
- Remove boundary around the Public checkbox
- Make 'Join' and 'Create' the primary green button (assuming they're greyed out because they're not clickable – can we make the not clickable state a .6 opacity or something?)

Hut
- Same treatment on 'Join' button

Tally
- Capitalize 'Submit'
- Same primary button treatment

**Comment by matildepark** [comment]
> Make 'Join' and 'Create' the primary green button (assuming they're greyed out because they're not clickable – can we make the not clickable state a .6 opacity or something?)

It's just the colour. There is no button disabled logic on this right now, it just uses `required` in the `<textbox>` to enforce it having something in it before hitting the button.

**Comment by gordoncc** [comment]
Ok, let's not worry about the disabled state for now.

**Review by gordoncc — APPROVED** [review]

**Review by tinnus-napbus — APPROVED** [review]

**Pull request merged**
